/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.beans.PropertyVetoException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Mohamed Achraf BEN MOHAMED<mohamedachraf@wanadoo.fr>
 */
public class ARAC_V01 extends javax.swing.JFrame {

    /**
     * Creates new form ARAC
     */
    public ARAC_V01() {

        initComponents();
        MenuTools.setMnemonic('T');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        AracMenuBar = new javax.swing.JMenuBar();
        MenuTools = new javax.swing.JMenu();
        SchemesConverter = new javax.swing.JMenuItem();
        CKYParser = new javax.swing.JMenuItem();
        CollocationsExtractor = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuTaggedSentences = new javax.swing.JMenuItem();
        MenuCollections = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARAC v0.1");
        setIconImages(null);
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setPreferredSize(new java.awt.Dimension(1024, 700));

        jLabel1.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bodyBackground.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setText("V0.1");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(697, 697, 697)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel4.setText("    ");
        jToolBar1.add(jLabel4);

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/S_converter.png"))); // NOI18N
        jToggleButton2.setToolTipText("Schemes Converter");
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setMaximumSize(new java.awt.Dimension(35, 25));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(35, 25));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(35, 25));
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton2);

        jLabel3.setText("    ");
        jToolBar1.add(jLabel3);

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_parsetree_.png"))); // NOI18N
        jToggleButton1.setToolTipText("CKY Parser");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setMaximumSize(new java.awt.Dimension(35, 25));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(35, 25));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(35, 25));
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        jLabel5.setText("    ");
        jToolBar1.add(jLabel5);

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_parsetree_corrector.png"))); // NOI18N
        jToggleButton6.setToolTipText("Parse Tree Corrector");
        jToggleButton6.setFocusable(false);
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton6);

        jLabel6.setText("    ");
        jToolBar1.add(jLabel6);

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_parsetree_database.png"))); // NOI18N
        jToggleButton4.setToolTipText("Tagged Sentences");
        jToggleButton4.setFocusable(false);
        jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton4);

        jLabel7.setText("    ");
        jToolBar1.add(jLabel7);
        jToolBar1.add(jSeparator3);

        jLabel8.setText("    ");
        jToolBar1.add(jLabel8);

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/property.png"))); // NOI18N
        jToggleButton5.setFocusable(false);
        jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton5.setMaximumSize(new java.awt.Dimension(29, 25));
        jToggleButton5.setMinimumSize(new java.awt.Dimension(29, 25));
        jToggleButton5.setPreferredSize(new java.awt.Dimension(29, 25));
        jToggleButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton5);

        jLabel9.setText("    ");
        jToolBar1.add(jLabel9);

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/collocations.png"))); // NOI18N
        jToggleButton3.setToolTipText("Collocations Extractor");
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setMaximumSize(new java.awt.Dimension(35, 25));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(35, 25));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(35, 25));
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton3);

        MenuTools.setMnemonic('T');
        MenuTools.setText("Tools");

        SchemesConverter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tree16x16.png"))); // NOI18N
        SchemesConverter.setMnemonic('S');
        SchemesConverter.setText("Schemes Converter");
        SchemesConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchemesConverterActionPerformed(evt);
            }
        });
        MenuTools.add(SchemesConverter);

        CKYParser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CKY_Algorithm.png"))); // NOI18N
        CKYParser.setMnemonic('C');
        CKYParser.setText("CKY Parser");
        CKYParser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CKYParserActionPerformed(evt);
            }
        });
        MenuTools.add(CKYParser);

        CollocationsExtractor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/collocations.png"))); // NOI18N
        CollocationsExtractor.setMnemonic('E');
        CollocationsExtractor.setText("Collocations Extractor");
        CollocationsExtractor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollocationsExtractorActionPerformed(evt);
            }
        });
        MenuTools.add(CollocationsExtractor);

        AracMenuBar.add(MenuTools);

        MenuEdit.setMnemonic('E');
        MenuEdit.setText("Edit");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/property.png"))); // NOI18N
        jMenuItem2.setText("Proprieties");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuEdit.add(jMenuItem2);

        MenuTaggedSentences.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taggedSentences.png"))); // NOI18N
        MenuTaggedSentences.setText("Tagged Sentences");
        MenuTaggedSentences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTaggedSentencesActionPerformed(evt);
            }
        });
        MenuEdit.add(MenuTaggedSentences);

        AracMenuBar.add(MenuEdit);

        MenuCollections.setMnemonic('C');
        MenuCollections.setText("Collections");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddDocument.png"))); // NOI18N
        jMenuItem5.setText("Add Document");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuCollections.add(jMenuItem5);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon16x16.png"))); // NOI18N
        jMenuItem3.setText("Search");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuCollections.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stats.png"))); // NOI18N
        jMenuItem4.setText("Corpus Statistics");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuCollections.add(jMenuItem4);

        AracMenuBar.add(MenuCollections);

        MenuHelp.setMnemonic('H');
        MenuHelp.setText("Help");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuHelp.add(jMenuItem1);

        AracMenuBar.add(MenuHelp);

        setJMenuBar(AracMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SchemesConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchemesConverterActionPerformed
        SchemesConvert converter = new SchemesConvert();
        Panel.removeAll();
        Panel.add(converter);
        converter.show();
        try {
            converter.setMaximum(Boolean.TRUE);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SchemesConverterActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void CKYParserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CKYParserActionPerformed
        CKYParse parse = new CKYParse();
        Panel.removeAll();
        Panel.add(parse);
        parse.show();
        try {
            parse.setMaximum(Boolean.TRUE);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CKYParserActionPerformed

    private void CollocationsExtractorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollocationsExtractorActionPerformed
        CollocationsExtract collocations = new CollocationsExtract();
        Panel.removeAll();
        Panel.add(collocations);
        collocations.show();
        try {
            collocations.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CollocationsExtractorActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            RulesManager manager = new RulesManager();
            Panel.removeAll();
            Panel.add(manager);
            manager.show();
            try {
                manager.setMaximum(Boolean.TRUE);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuTaggedSentencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTaggedSentencesActionPerformed
        TaggedSentences taggedSentences = null;
        try {
            taggedSentences = new TaggedSentences();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel.removeAll();
        Panel.add(taggedSentences);
        taggedSentences.show();
        try {
            taggedSentences.setMaximum(Boolean.TRUE);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuTaggedSentencesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        DocumentsSearch search = null;
        try {
            search = new DocumentsSearch();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel.removeAll();
        Panel.add(search);
        search.show();

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CorpusStatistics corpusStatistics = null;
        try {
            corpusStatistics = new CorpusStatistics();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel.removeAll();
        Panel.add(corpusStatistics);
        corpusStatistics.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        CorpusAddDocument adddoc = null;
        adddoc = new CorpusAddDocument();
        Panel.removeAll();
        Panel.add(adddoc);
        adddoc.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        CKYParse parse = new CKYParse();
        Panel.removeAll();
        Panel.add(parse);
        parse.show();
        try {
            parse.setMaximum(Boolean.TRUE);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        SchemesConvert converter = new SchemesConvert();
        Panel.removeAll();
        Panel.add(converter);
        converter.show();
        try {
            converter.setMaximum(Boolean.TRUE);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        CollocationsExtract collocations = new CollocationsExtract();
        Panel.removeAll();
        Panel.add(collocations);
        collocations.show();
        try {
            collocations.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        TaggedSentences taggedSentences = null;
        try {
            taggedSentences = new TaggedSentences();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel.removeAll();
        Panel.add(taggedSentences);
        taggedSentences.show();
        try {
            taggedSentences.setMaximum(Boolean.TRUE);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        try {
            RulesManager manager = new RulesManager();
            Panel.removeAll();
            Panel.add(manager);
            manager.show();
            try {
                manager.setMaximum(Boolean.TRUE);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        ParseTreeCorrector corrector = null;
        try {
            corrector = new ParseTreeCorrector();
        } catch (IOException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
        Panel.removeAll();
        Panel.add(corrector);
        corrector.show();
        try {
            corrector.setMaximum(Boolean.TRUE);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jToggleButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /*
             * Set the Nimbus look and feel
             */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /*
             * If Nimbus (introduced in Java SE 6) is not available, stay with the
             * default look and feel. For details see
             * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(ARAC_V01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

            /*
             * Create and display the form
             */
            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    new ARAC_V01().setVisible(true);
                }
            });
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ARAC_V01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AracMenuBar;
    private javax.swing.JMenuItem CKYParser;
    private javax.swing.JMenuItem CollocationsExtractor;
    private javax.swing.JMenu MenuCollections;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenuItem MenuTaggedSentences;
    private javax.swing.JMenu MenuTools;
    private javax.swing.JPanel Panel;
    private javax.swing.JMenuItem SchemesConverter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
