/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.Utils;
import aracplatform.CollocationsExtractor;
import java.awt.ComponentOrientation;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Mohamed Achraf BEN MOHAMED<mohamedachraf@wanadoo.fr>
 */
public class CollocationsExtract extends javax.swing.JInternalFrame {

    /**
     * Creates new form CollocationsExtract
     */
    public CollocationsExtract() {
        initComponents();
        CollocationList.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        CollocationContext.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCollocationsMeasures = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CollocationList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CollocationContext = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        MI = new javax.swing.JRadioButton();
        LR = new javax.swing.JRadioButton();
        TT = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        FileSource1 = new javax.swing.JTextField();
        ButtonChooseFile1 = new javax.swing.JButton();
        ButtonLoad1 = new javax.swing.JButton();
        CollocationsNumber = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        CollocationSize = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Collocations Extractor");
        setPreferredSize(new java.awt.Dimension(1024, 700));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Collocations"));

        jScrollPane2.setViewportView(CollocationList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Context"));

        CollocationContext.setColumns(20);
        CollocationContext.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        CollocationContext.setRows(5);
        jScrollPane1.setViewportView(CollocationContext);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Measures"));

        buttonGroupCollocationsMeasures.add(MI);
        MI.setText("Mutual Information");

        buttonGroupCollocationsMeasures.add(LR);
        LR.setSelected(true);
        LR.setText("Likelihood Ratios");

        buttonGroupCollocationsMeasures.add(TT);
        TT.setText("T test");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LR)
                    .addComponent(TT)
                    .addComponent(MI))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(LR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Source File"));

        ButtonChooseFile1.setText("Choose File");
        ButtonChooseFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseFile1ActionPerformed(evt);
            }
        });

        ButtonLoad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start.png"))); // NOI18N
        ButtonLoad1.setText("Load & Process");
        ButtonLoad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonLoad1MousePressed(evt);
            }
        });
        ButtonLoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoad1ActionPerformed(evt);
            }
        });

        CollocationsNumber.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Collocations Number");

        CollocationSize.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Collocations Size");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CollocationsNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(CollocationSize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonLoad1))
                    .addComponent(FileSource1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(ButtonChooseFile1)
                .addGap(197, 197, 197))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileSource1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChooseFile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CollocationsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CollocationSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ButtonLoad1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonChooseFile1, FileSource1});

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CollocationSize, CollocationsNumber});

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoad1ActionPerformed
        CollocationsExtractor extractor = new CollocationsExtractor();
        DefaultListModel model = new DefaultListModel();
        //------------
        final Utils utils = new Utils();
        
        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {         
                    CollocationContext.setText("");
                    String Coll = CollocationList.getSelectedValue().toString();                    
                    int start = 0;
                    
                    try {
            String SourceTexte = utils.LoadFileToStringByPath(FileSource1.getText());
            int found = SourceTexte.indexOf(Coll, start);
            int cpt =1;
                    while (found != -1) {                                                             
                        String CollContext="";                        
                        //---                                         
                        for (int i = found-50; i < found; i++) {
                            if(i>0 && i< SourceTexte.length())
                                CollContext = CollContext+ SourceTexte.charAt(i);
                        }
                        CollocationContext.append("["+cpt+"]..."+CollContext);                      
                        cpt++;
                        //---
                        CollContext="";
                        //---
                        for (int i = found; i < found+Coll.length(); i++) {
                            if(i>0 && i< SourceTexte.length())
                                CollContext = CollContext+ SourceTexte.charAt(i);
                        }
                        CollocationContext.append("["+CollContext+ "]");                       
                        //---
                        CollContext="";
                        //---
                        for (int i = found+Coll.length(); i < found+50; i++) {
                            if(i>0 && i< SourceTexte.length())
                                CollContext = CollContext+ SourceTexte.charAt(i);
                        }
                        CollocationContext.append(CollContext);         
                        //---
                        start = found + Coll.length();   
                        CollocationContext.append("\n");
                        found = SourceTexte.indexOf(Coll, start);  
                    }
        } catch (IOException ex) {
            Logger.getLogger(CollocationsExtract.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
                    
                    
                }
            }
        };
        CollocationList.addMouseListener(mouseListener);
        //------------
        CollocationList.setModel(model);
        File file = new File(FileSource1.getText());
        int NumberOfCollocations = Integer.valueOf(CollocationsNumber.getModel().getValue().toString());
        int SizeOfCollocations = Integer.valueOf(CollocationSize.getModel().getValue().toString());
        int UsedMethod = 1;
        if (LR.isSelected()) {
            UsedMethod = 1;
        } else if (TT.isSelected()) {
            UsedMethod = 3;
        } else if (MI.isSelected()) {
            UsedMethod = 2;
        }

        if (SizeOfCollocations == 2) {
            CollocationContext.setText("");
            try {
                Map<String, Double> Collocations = extractor.ExtractTwoWordsSizeCollocationsFromFile(file, NumberOfCollocations, UsedMethod);
                for (Entry entry : Collocations.entrySet()) {
                    model.addElement(entry.getKey());
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CollocationsExtract.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (SizeOfCollocations == 3) {
            CollocationContext.setText("");
            try {
                Map<String, Double> Collocations = extractor.ExtractThreeWordsSizeCollocationsFromFile(file, NumberOfCollocations, UsedMethod);
                for (Entry entry : Collocations.entrySet()) {
                    model.addElement(entry.getKey());
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CollocationsExtract.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (SizeOfCollocations == 4) {
            CollocationContext.setText("");
            try {
                Map<String, Double> Collocations = extractor.ExtractFoorWordsSizeCollocationsFromFile(file, NumberOfCollocations, UsedMethod);
                for (Entry entry : Collocations.entrySet()) {
                    model.addElement(entry.getKey());
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CollocationsExtract.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_ButtonLoad1ActionPerformed

    private void ButtonChooseFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseFile1ActionPerformed
        JFileChooser DevSetChooser = new JFileChooser("D:/Development/java_projects/AracPlatform_V0.1/data/");
        DevSetChooser.showOpenDialog(null);
        File f = DevSetChooser.getSelectedFile();
        String sourcefile = f.getAbsolutePath();
        FileSource1.setText(sourcefile);
    }//GEN-LAST:event_ButtonChooseFile1ActionPerformed

    private void ButtonLoad1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLoad1MousePressed
        
    }//GEN-LAST:event_ButtonLoad1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonChooseFile1;
    private javax.swing.JButton ButtonLoad1;
    private javax.swing.JTextArea CollocationContext;
    private javax.swing.JList CollocationList;
    private javax.swing.JSpinner CollocationSize;
    private javax.swing.JSpinner CollocationsNumber;
    private javax.swing.JTextField FileSource1;
    private javax.swing.JRadioButton LR;
    private javax.swing.JRadioButton MI;
    private javax.swing.JRadioButton TT;
    private javax.swing.ButtonGroup buttonGroupCollocationsMeasures;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
