/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.Utils;
import aracplatform.PostingList;
import java.awt.ComponentOrientation;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author user
 */
public class CorpusAddDocument extends javax.swing.JInternalFrame {

    /**
     * Creates new form CorpusAddDocument
     */
    public CorpusAddDocument() {
        initComponents();
        DocumentContent.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        DocumentTitle.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DocumentSourceFile = new javax.swing.JTextField();
        ChooseFileButton = new javax.swing.JButton();
        LoadDocumentButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DocumentContent = new javax.swing.JTextArea();
        SaveDocumentButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DocumentTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DocumentSize = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1024, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Document"));

        ChooseFileButton.setText("Choose file");
        ChooseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseFileButtonActionPerformed(evt);
            }
        });

        LoadDocumentButton.setText("Load document");
        LoadDocumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadDocumentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DocumentSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChooseFileButton))
                    .addComponent(LoadDocumentButton))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocumentSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChooseFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoadDocumentButton))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ChooseFileButton, DocumentSourceFile});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Document Details"));

        DocumentContent.setColumns(20);
        DocumentContent.setLineWrap(true);
        DocumentContent.setRows(5);
        jScrollPane1.setViewportView(DocumentContent);

        SaveDocumentButton.setText("Save Document");
        SaveDocumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDocumentButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Document Title");

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Document Size");

        DocumentSize.setForeground(new java.awt.Color(153, 153, 153));
        DocumentSize.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DocumentSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveDocumentButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DocumentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DocumentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SaveDocumentButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(DocumentSize))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DocumentTitle, jLabel1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseFileButtonActionPerformed
        JFileChooser DevSetChooser = new JFileChooser("D:/java_projects/AracPlatform_V0.1/data/");
        DevSetChooser.showOpenDialog(null);
        File f = DevSetChooser.getSelectedFile();
        String sourcefile = f.getAbsolutePath();
        DocumentSourceFile.setText(sourcefile);
    }//GEN-LAST:event_ChooseFileButtonActionPerformed

    private void LoadDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadDocumentButtonActionPerformed
        ArrayList<String> words = new ArrayList<>();
        Utils utils = new Utils();
        
        File filesource = new File(DocumentSourceFile.getText());
        try {
            words = utils.LoadFileToArrayList(filesource);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CorpusAddDocument.class.getName()).log(Level.SEVERE, null, ex);
        }
        String document ="";
        for(String word : words){
            document += word+" ";
        }        
        DocumentContent.setAlignmentY(RIGHT_ALIGNMENT);
        DocumentContent.setText(document);
        DocumentSize.setText(String.valueOf(words.size()));
    }//GEN-LAST:event_LoadDocumentButtonActionPerformed

    private void SaveDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDocumentButtonActionPerformed
        
        Utils utils = new Utils();
        File PLDictionnary = new File("F:\\tmp\\321\\PLdictionnary.txt");        
        File PLPostingList = new File("F:\\tmp\\321\\PLPostingList.txt");  
        File PLStatistics  = new File("F:\\tmp\\321\\PLStatistics.txt");  
        File TEMP  = new File("F:\\tmp\\321\\77.txt");  
        try {
            utils.SaveStringToFile(DocumentContent.getText(), TEMP);
        } catch (IOException ex) {
            Logger.getLogger(CorpusAddDocument.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PostingList postingList = new PostingList();
        try {        
            postingList.Update(TEMP, PLDictionnary, PLPostingList, PLStatistics);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CorpusAddDocument.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CorpusAddDocument.class.getName()).log(Level.SEVERE, null, ex);
        }
        DocumentContent.setText("");
        DocumentSourceFile.setText("");
        
    }//GEN-LAST:event_SaveDocumentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseFileButton;
    private javax.swing.JTextArea DocumentContent;
    private javax.swing.JLabel DocumentSize;
    private javax.swing.JTextField DocumentSourceFile;
    private javax.swing.JTextField DocumentTitle;
    private javax.swing.JButton LoadDocumentButton;
    private javax.swing.JButton SaveDocumentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
