/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.Utils;
import aracplatform.SchemesConverter;
import aracplatform.SchemesParser;
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.Format;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Mohamed Achraf BEN MOHAMED<mohamedachraf@wanadoo.fr>
 */
public class SchemesConvert extends javax.swing.JInternalFrame {

    /**
     * Creates new form SchemesConverter
     */
    public SchemesConvert() {
        initComponents();    
        ProgressBar.setVisible(false);
        
        TextField.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        SchemesField.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ButtonLoadFile = new javax.swing.JButton();
        FileSouce = new javax.swing.JTextField();
        ButtonLoadSourceFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextField = new javax.swing.JTextArea();
        ButtonPaste = new javax.swing.JButton();
        ButtonSchemesConversion = new javax.swing.JButton();
        Mashkoul = new javax.swing.JCheckBox();
        WithSplit = new javax.swing.JCheckBox();
        LargeText = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SchemesField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Accuracy = new javax.swing.JTextField();
        ProgressBar = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setTitle("Schemes Converter");
        setPreferredSize(new java.awt.Dimension(1024, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Text Source File"));

        ButtonLoadFile.setText("Choose File");
        ButtonLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoadFileActionPerformed(evt);
            }
        });

        ButtonLoadSourceFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_file.gif"))); // NOI18N
        ButtonLoadSourceFile.setToolTipText("Load");
        ButtonLoadSourceFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoadSourceFileActionPerformed(evt);
            }
        });

        TextField.setColumns(20);
        TextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TextField.setLineWrap(true);
        TextField.setRows(5);
        jScrollPane1.setViewportView(TextField);

        ButtonPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paste.gif"))); // NOI18N
        ButtonPaste.setToolTipText("Paste");
        ButtonPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPasteActionPerformed(evt);
            }
        });

        ButtonSchemesConversion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start.png"))); // NOI18N
        ButtonSchemesConversion.setText("Convert to Schemes");
        ButtonSchemesConversion.setToolTipText("Convert to Schemes");
        ButtonSchemesConversion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonSchemesConversionMousePressed(evt);
            }
        });
        ButtonSchemesConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSchemesConversionActionPerformed(evt);
            }
        });

        Mashkoul.setSelected(true);
        Mashkoul.setText("Mashkoul");
        Mashkoul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MashkoulActionPerformed(evt);
            }
        });

        WithSplit.setSelected(true);
        WithSplit.setText("With Split");

        LargeText.setText("Large Text");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(FileSouce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonLoadFile))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonSchemesConversion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonPaste, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonLoadSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WithSplit)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mashkoul)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LargeText)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileSouce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLoadFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ButtonPaste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonSchemesConversion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mashkoul)
                            .addComponent(LargeText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WithSplit))
                    .addComponent(ButtonLoadSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonLoadSourceFile, ButtonPaste, ButtonSchemesConversion});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Schemes Conversion"));

        SchemesField.setColumns(20);
        SchemesField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        SchemesField.setLineWrap(true);
        SchemesField.setRows(5);
        jScrollPane2.setViewportView(SchemesField);

        jLabel1.setText("Accuracy");

        Accuracy.setEditable(false);
        Accuracy.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        Accuracy.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ProgressBar.setToolTipText("");
        ProgressBar.setValue(100);
        ProgressBar.setString("converting...");
        ProgressBar.setStringPainted(true);
        ProgressBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProgressBarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_konsole_content.png"))); // NOI18N
        jButton1.setToolTipText("Delete Contents");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoadFileActionPerformed
        JFileChooser DevSetChooser = new JFileChooser("D:/Development/java_projects/AracPlatform_V0.1/data/");
        DevSetChooser.showOpenDialog(null);
        File f = DevSetChooser.getSelectedFile();
        String sourcefile = f.getAbsolutePath();
        FileSouce.setText(sourcefile);
    }//GEN-LAST:event_ButtonLoadFileActionPerformed

    private void ButtonLoadSourceFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoadSourceFileActionPerformed

        ArrayList<String> words = new ArrayList<>();
        Utils utils = new Utils();
        try{
        File filesource = new File(FileSouce.getText());
        words = utils.LoadFileToArrayList(filesource);
        }catch(Exception e){

        }
        String document ="";
        for(String word : words){
            document += word+" ";
        }        
        TextField.setAlignmentY(RIGHT_ALIGNMENT);
        TextField.setText(document);
    }//GEN-LAST:event_ButtonLoadSourceFileActionPerformed

    private void ButtonPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPasteActionPerformed
           Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable contents = clipboard.getContents(null);
        try {
            TextField.setText((String)contents.getTransferData(DataFlavor.stringFlavor));
        } catch (UnsupportedFlavorException | IOException ex) {
            Logger.getLogger(CKYParse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonPasteActionPerformed

    private void ButtonSchemesConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSchemesConversionActionPerformed

        ArrayList<String> source = new ArrayList<>();
        ArrayList<String> result = new ArrayList<>();
        ArrayList<String> resultTMP = new ArrayList<>();        
        SchemesConverter converter = new SchemesConverter();
        SchemesParser parser = new SchemesParser();
        String text = TextField.getText().trim(); 
        text = text.replaceAll("[\\.,;:!?،]", " . ");
        text = text.replaceAll("  ", " ");
        TextField.setText(text);
        String[] words = text.split("\\s");

        source.addAll(Arrays.asList(words));
//        for (int i = 0; i < words.length; i++) {
//            if(!words[i].matches("[\\s]+"))
//                source.add(words[i]);
//        }
        
            Boolean mashkoul  = Mashkoul.isSelected();
            Boolean withSplit = WithSplit.isSelected();
            Boolean largetext = LargeText.isSelected();
            
        
            if(largetext == Boolean.TRUE){
            try {
                resultTMP = converter.ShemesConvert(source, mashkoul,withSplit);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SchemesConvert.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
            try {
                resultTMP = parser.SchemesConvert(source, mashkoul,withSplit);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SchemesConvert.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SchemesConvert.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            
        
        //**************************Formatting returned result
        for(String w : resultTMP){
            String[] s = w.split("\\|");
            result.add(s[0]);
        }

        //**************************Computing Accuracy
        double sc = 0.0, acc = 0.0;
        for (String s : result) {
            if (s.contains("_مجهول_")) {
                sc++;
            }
        }
        Format format = new DecimalFormat("###.##");
        String accuarcy = format.format(Double.valueOf(100 - (sc / (double) result.size()) * 100));
        Accuracy.setText(accuarcy + " %");
        //**************************
        String res = "";
        for (String w : result) {
            res += w + " ";
        }
        SchemesField.setAlignmentX(RIGHT_ALIGNMENT);
        SchemesField.setText(res);
        ProgressBar.setVisible(false);
    }//GEN-LAST:event_ButtonSchemesConversionActionPerformed

    private void MashkoulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MashkoulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MashkoulActionPerformed

    private void ProgressBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProgressBarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgressBarMousePressed

    private void ButtonSchemesConversionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSchemesConversionMousePressed
        ProgressBar.setVisible(true);
    }//GEN-LAST:event_ButtonSchemesConversionMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SchemesField.setText("");
        TextField.setText("");
        Accuracy.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Accuracy;
    private javax.swing.JButton ButtonLoadFile;
    private javax.swing.JButton ButtonLoadSourceFile;
    private javax.swing.JButton ButtonPaste;
    private javax.swing.JButton ButtonSchemesConversion;
    private javax.swing.JTextField FileSouce;
    private javax.swing.JCheckBox LargeText;
    private javax.swing.JCheckBox Mashkoul;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JTextArea SchemesField;
    private javax.swing.JTextArea TextField;
    private javax.swing.JCheckBox WithSplit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
